name: "Publish eda-modbus-bridge"

# Run manually only
on: workflow_dispatch

jobs:
  build:
    name: Publish eda-modbus-bridge
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Publish ha-yc-backup
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ha-yc-backup
